library(tidyverse)
View(iris)
ggplot(data=iris) + geom_point(mapping = aes(x=Petal.Width, y=Petal.Length, color=Species))
km <- kmeans(iris[,3:4], centers = 3)
km$centers
ggplot(data=iris) + geom_point(mapping = aes(x=Petal.Width, y=Petal.Length, color=Species)) + geom_point(data=km$centers, mapping = aes(x=Petal.Width, y=Petal.Length, color=Species))
class(km$centers)
class(as.data.frame(km$centers))
ggplot(data=iris) + geom_point(mapping = aes(x=Petal.Width, y=Petal.Length, color=Species)) + geom_point(data=as.data.frame(km$centers), mapping = aes(x=Petal.Width, y=Petal.Length, color=Species))
ggplot(data=iris) + geom_point(mapping = aes(x=Petal.Width, y=Petal.Length, color=Species)) + geom_point(data=as.data.frame(km$centers), mapping = aes(x=Petal.Width, y=Petal.Length), color="red")
ggplot(data=iris) + geom_point(mapping = aes(x=Petal.Width, y=Petal.Length, color=Species)) + geom_point(data=as.data.frame(km$centers), mapping = aes(x=Petal.Width, y=Petal.Length), color="red", size=5)
km$cluster
table(iris$Species, km$cluster)
km <- kmeans(iris[,3:4], centers = 3)
table(iris$Species, km$cluster)
km <- kmeans(iris[,3:4], centers = 3, nstart = 2)
table(iris$Species, km$cluster)
ggplot(data=iris) + geom_point(mapping = aes(x=Petal.Width, y=Petal.Length, color=Species)) + geom_point(data=as.data.frame(km$centers), mapping = aes(x=Petal.Width, y=Petal.Length), color="red", size=5)
km <- kmeans(iris[,1:4], centers = 3)
table(iris$Species, km$cluster)
ggplot(data=iris) + geom_point(mapping = aes(x=Petal.Width, y=Petal.Length, color=Species)) + geom_point(data=as.data.frame(km$centers), mapping = aes(x=Petal.Width, y=Petal.Length), color="red", size=5)
km <- kmeans(iris[,1:4], centers = 3)
table(iris$Species, km$cluster)
